export { default as HomePage } from './Home'
export { default as RegisterPage } from './Register'
export { default as LoginPage } from './Login'
export { default as AboutPage } from './About'
export { default as AddEditPage } from './AddEdit'
